### PR TITLE
Italian Translation of msg/json/it.json and some other minor translations in tests 

### PR DESCRIPTION
**Pull request by eziosoma**
This is the first pull request after the completion of the translation and tests.
Some issues due to Italian strings not completely shown in the blocks. Refer to email to my email to Michael Bonani.

### CODE REVIEW

**Comment by stephanemagnenat** [comment]
Thank you very much for this work! I will see with Michael tomorrow.

**Comment by FrancescoMondada** [comment]
Grande Ezio!!!!!!
Grazie mille, eccellente

```
                Franncesco
```

**Comment by eziosoma** [comment]
It was really a pleasure for me and Federico to contribute to the Thymio project!

**Comment by mbonani** [comment]
Dear Ezio and  Federico
We integrate your translation directly in commit 104727034ebddc78aa875850c3b8694d8aae8616 rebasing all in one unique commit. We can now close your pull request and you can checkout master. 
We also fix the problem of ellipsis 
Thank you very much for your contribution

**Pull request closed without merging**
