### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by fboteroh**
Spanish translation finished :)

### CODE REVIEW

**Comment by FrancescoMondada** [comment]
Thank you!!!!!!!!

```
            Francesco
```

On 9 févr. 2016, at 03:07, Francisco Botero notifications@github.com wrote:

> Spanish translation finished :)
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/aseba-community/blockly/pull/4
> 
> Commit Summary
> 
> Update es.json
> Update es.json
> Update es.json
> Rename playground.fr.html to playground.es.html
> Update playground.es.html
> Update playground.es.html
> Create viewtests.es.html
> Create asebastudio.es.html
> Update playground.es.html
> Update asebastudio.es.html
> Update es.json
> Update es.json
> Update es.json
> Update playground.es.html
> Update es.json
> Update es.json
> Update es.json
> Update es.json
> Update es.json
> File Changes
> 
> M msg/json/es.json (422)
> A tests/aesl/viewtests.es.html (188)
> A tests/asebastudio.es.html (502)
> A tests/playground.es.html (578)
> Patch Links:
> 
> https://github.com/aseba-community/blockly/pull/4.patch
> https://github.com/aseba-community/blockly/pull/4.diff
> —
> Reply to this email directly or view it on GitHub.

---

Prof. Francesco Mondada
Mobile robots architecture & design

Ecole Polytechnique Fédérale de Lausanne (EPFL)
Laboratoire de Systèmes Robotiques (LSRO)

In sabbatical at the:
Artificial Life Lab
Department of Zoology
Karl Franzens University Graz, Austria

Postal address:
Francesco Mondada 
EPFL  - STI  - IMT - LSRO 
bureau MEB3426, Station 9
CH-1015 Lausanne, Switzerland

tel: +41 21 693 73 57
fax: +41 21 693 78 07
http://lsro.epfl.ch

**Comment by fboteroh** [comment]
It is my pleasure to contribute my bit to this amazing project.

My best,

## 

Francisco

De: Francesco Mondada [mailto:notifications@github.com]
Enviado el: martes, 09 de febrero de 2016 02:10 a.m.
Para: aseba-community/blockly blockly@noreply.github.com
CC: Francisco Javier Botero Herrera fboteroh@eafit.edu.co
Asunto: Re: [blockly] Patch 1 (#4)

Thank you!!!!!!!!

Francesco

On 9 févr. 2016, at 03:07, Francisco Botero <notifications@github.com<mailto:notifications@github.com>> wrote:

> Spanish translation finished :)
> 
> You can view, comment on, or merge this pull request online at:
> 
> https://github.com/aseba-community/blockly/pull/4
> 
> Commit Summary
> 
> Update es.json
> Update es.json
> Update es.json
> Rename playground.fr.html to playground.es.html
> Update playground.es.html
> Update playground.es.html
> Create viewtests.es.html
> Create asebastudio.es.html
> Update playground.es.html
> Update asebastudio.es.html
> Update es.json
> Update es.json
> Update es.json
> Update playground.es.html
> Update es.json
> Update es.json
> Update es.json
> Update es.json
> Update es.json
> File Changes
> 
> M msg/json/es.json (422)
> A tests/aesl/viewtests.es.html (188)
> A tests/asebastudio.es.html (502)
> A tests/playground.es.html (578)
> Patch Links:
> 
> https://github.com/aseba-community/blockly/pull/4.patch
> https://github.com/aseba-community/blockly/pull/4.diff
> —
> Reply to this email directly or view it on GitHub.

---

Prof. Francesco Mondada
Mobile robots architecture & design

Ecole Polytechnique Fédérale de Lausanne (EPFL)
Laboratoire de Systèmes Robotiques (LSRO)

In sabbatical at the:
Artificial Life Lab
Department of Zoology
Karl Franzens University Graz, Austria

Postal address:
Francesco Mondada
EPFL - STI - IMT - LSRO
bureau MEB3426, Station 9
CH-1015 Lausanne, Switzerland

tel: +41 21 693 73 57
fax: +41 21 693 78 07
http://lsro.epfl.ch

—
Reply to this email directly or view it on GitHubhttps://github.com/aseba-community/blockly/pull/4#issuecomment-181740065.

"La información contenida en este correo electrónico está dirigida únicamente a su destinatario y puede contener información confidencial, material privilegiado o información protegida por derecho de autor. Está prohibida cualquier copia, utilización, indebida retención, modificación, difusión, distribución o reproducción total o parcial. Si usted recibe este mensaje por error, por favor contacte al remitente y elimínelo. La información aquí contenida es responsabilidad exclusiva de su remitente por lo tanto la Universidad EAFIT no se hace responsable de lo que el mensaje contenga."

"The information contained in this email is addressed to its recipient only and may contain confidential information, privileged material or information protected by copyright. Its prohibited any copy, use, improper retention, modification, dissemination, distribution or total or partial reproduction. If you receive this message by error, please contact the sender and delete it. The information contained herein is the sole responsibility of the sender therefore Universidad EAFIT is not responsible for what the message contains."

"La información contenida en este correo electrónico está dirigida únicamente a su destinatario y puede contener información confidencial, material privilegiado o información protegida por derecho de autor. Está prohibida cualquier copia, utilización, indebida retención, modificación, difusión, distribución o reproducción total o parcial. Si usted recibe este mensaje por error, por favor contacte al remitente y elimínelo. La información aquí contenida es responsabilidad exclusiva de su remitente por lo tanto la Universidad EAFIT no se hace responsable de lo que el mensaje contenga."

"The information contained in this email is addressed to its recipient only and may contain confidential information, privileged material or information protected by copyright. Its prohibited any copy, use, improper retention, modification, dissemination, distribution or total or partial reproduction. If you receive this message by error, please contact the sender and delete it. The information contained herein is the sole responsibility of the sender therefore Universidad EAFIT is not responsible for what the message contains."

**Comment by mbonani** [comment]
Dear Francisco,
We integrate your translation directly in commit 3989b1fd907714efd856dc14f284fec1852c06ba
rebasing all in one unique commit. We can now close your pull request and you can checkout master. 

Thank you very much for your contribution

**Comment by fboteroh** [comment]
Michael,

Thank you so much. It is my pleasure to be involved in this project. Please let me know if further review is required.

At your disposal I remain.

## 

Francisco Botero

De: Michael Bonani [mailto:notifications@github.com]
Enviado el: miércoles, 10 de febrero de 2016 08:15 a.m.
Para: aseba-community/blockly blockly@noreply.github.com
CC: Francisco Javier Botero Herrera fboteroh@eafit.edu.co
Asunto: Re: [blockly] Patch 1 (#4)

Dear Francisco,
We integrate your translation directly in commit 3989b1fhttps://github.com/aseba-community/blockly/commit/3989b1fd907714efd856dc14f284fec1852c06ba
rebasing all in one unique commit. We can now close your pull request and you can checkout master.

Thank you very much for your contribution

—
Reply to this email directly or view it on GitHubhttps://github.com/aseba-community/blockly/pull/4#issuecomment-182368648.

"La información contenida en este correo electrónico está dirigida únicamente a su destinatario y puede contener información confidencial, material privilegiado o información protegida por derecho de autor. Está prohibida cualquier copia, utilización, indebida retención, modificación, difusión, distribución o reproducción total o parcial. Si usted recibe este mensaje por error, por favor contacte al remitente y elimínelo. La información aquí contenida es responsabilidad exclusiva de su remitente por lo tanto la Universidad EAFIT no se hace responsable de lo que el mensaje contenga."

"The information contained in this email is addressed to its recipient only and may contain confidential information, privileged material or information protected by copyright. Its prohibited any copy, use, improper retention, modification, dissemination, distribution or total or partial reproduction. If you receive this message by error, please contact the sender and delete it. The information contained herein is the sole responsibility of the sender therefore Universidad EAFIT is not responsible for what the message contains."

"La información contenida en este correo electrónico está dirigida únicamente a su destinatario y puede contener información confidencial, material privilegiado o información protegida por derecho de autor. Está prohibida cualquier copia, utilización, indebida retención, modificación, difusión, distribución o reproducción total o parcial. Si usted recibe este mensaje por error, por favor contacte al remitente y elimínelo. La información aquí contenida es responsabilidad exclusiva de su remitente por lo tanto la Universidad EAFIT no se hace responsable de lo que el mensaje contenga."

"The information contained in this email is addressed to its recipient only and may contain confidential information, privileged material or information protected by copyright. Its prohibited any copy, use, improper retention, modification, dissemination, distribution or total or partial reproduction. If you receive this message by error, please contact the sender and delete it. The information contained herein is the sole responsibility of the sender therefore Universidad EAFIT is not responsible for what the message contains."

**Pull request closed without merging**
